### ISSUE TITLE
[RFC] Simple way to generate basic sequences

### ISSUE THREAD

**Issue by desa** [influxdata/ifql#161]
I'm thinking of something along the lines of [`!R` from K](https://en.wikipedia.org/wiki/K_(programming_language) ) or possibly even [Streams from Scheme](https://www.gnu.org/software/mit-scheme/documentation/mit-scheme-ref/Streams.html) .

This is particularly useful when trying to learn how a language works.

The current process for gaining intuition with InfluxQL is
* create dummy database
* load a database with some dummy data
   - usually by running a few `insert x v=1`
* query dummy data until I've got a solid idea of what I want
* add some tags to that data
    - usually reinserting the same data I had previously, but this time with a few extra tags
* forget to drop old database

The process for learning tickscript is even more involved, since it involves often inserting a bunch of `log` and generating a stream of data and watching the kapacitor logs.

Both methods have relatively long feedback loops for gaining intuition about how the language works. We should attempt to make this feedback loop shorter.

For the purpose of learn-ability, I believe that having a way to generate simple sequences is preferential to having IFQL be able to read and operate on raw line protocol, because it allows the user to keep their thought process on a single file (rather than have to jump back and forth between the data file and the query file).

My general proposal would look something like the following

```js
generate(
start:-1m,
interval: 10s,
seed: 0,
next: function(prev) { return prev + 1 },
tags: ['t=a']
)
```

Which would generate the following data

```
t=a 0 0s
t=a 1 10s
t=a 2 20s
t=a 3 30s
t=a 4 40s
t=a 5 50s
```

**Comment by nathanielc** [comment]
@desa I like the idea of closing the feedback loop so that IFQL can be easily explored in a single session.

I also like the idea of using a `generate` function instead of allowing the user to specify raw points as that makes it clear that IFQL is not used to insert data. In fact there is no need to even write the data back to the database if you have  a generate function, you can simply chain off that function.

It feels a bit synthetic, meaning learning to use the generate function doesn't really help in normal use beyond just a simple play ground. But that synthetic environment seems like a great way for a new user to get exposed to the language. I am imagining a play.golang.org tour built into Chronograf where the first few examples are all using synthetic data. That seems like it could really help a user get a jump start on the mechanics of IFQL the language.

One concern is that going to play.golang.org is what a software dev would do to learn a new language because they have recognized that having a grasps of the basics of a new language is really important. I think that a typical user, though will want to first write queries that work off their existing data. So we should maybe think of how we can or if we should encourage users to take the language tour early in their learning process.

**Comment by desa** [comment]
@nathanielc Completely agree with most of the points you bring up. There are a couple premises I think I'd question

> I think that a typical user, though will want to first write queries that work off their existing data.

I'm not 100% sold that this is true. It assumes that (1) they understand the influxdb data model (2) the user has an influxdb instance with data that they can interact with (3) they understand the data shape in that instance well enough to be able to query it effectively.

> It feels a bit synthetic, meaning learning to use the generate function doesn't really help in normal use beyond just a simple play ground.

Completely agree that it's 100% synthetic. This is placing learnability as a first class citizen of the query language. I'd argue that this reduces the overhead for new users unfamiliar to the InfluxData ecosystem. 

>  So we should maybe think of how we can or if we should encourage users to take the language tour early in their learning process.

This is a good point, however I think that having the features also built in to the language would be useful. Much in the way that you have access to all of Go in the go playground.

One thing I think I should be clear about is that I'm operating under the assumption that our target audience is mostly people who are new to InfluxDB, and that having a shorter synthetic feedback loop will increase usability. It's entirely possible that this premise is incorrect.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/327)
