### ISSUE TITLE
Wildcards in IFQL

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ifql#295]
Wildcards present a challenge to the IFQL language because the essentially represent the set of all possible values.  While its easy to represent an empty set (i.e an empty list []) its not easy to represent a set of all values without some special indicator.

A special indicator becomes challenging because what is its type? A list? If so can you iterate over it? Do we need to add the concept of lazy evaluation to IFQL in order to accurately represent wildcards? That seems too complex.

An alternative solution is to define the set via subtraction. We already do this with the `group` function. You can group by all tags except `host` with `group(except:["host"])`. So what does this mean `group(except:[])`? That could mean group by everything. In contrast `group(by:[])` means group by nothing. The `except` and `by` arguments are mutually exclusive. So `group(by:[], except:[])` would be an error. This means we would need to be able to distinguish between an empty set and a non existent set. This can be accomplished with `nil`.

The `group` function would be:
```
group = (by=nil,except=nil,keep=nil) => ...
```

Therefore:

* group(by:[]) - means group by nothing
* group(except:[]) - means group by everything
* group(by:["host"]) - means group by host
* group() - would be an error since nothing was specified.
* etc.

**Comment by aanthony1243** [comment]
similar to window, I think that requiring the by:[]   (or except:)  is useful to remind the customer what's happening.  

If we introduce nil  here, would we consider delivering it as a compatible type in other situations, e.g. for _value?  

Finally,  this only covers the case of  `group by *`   it doesn't cover larger-scale pattern matching, e.g. `group by "user_*"`    

for the cases above, and also for `*`  it may make more sense to consider wild-cards as if they are expanding into a list.  Typically the context for a wildcard is well-defined so that we can use a meta-query to get all column names and then replace the expression with a list internally.  

We could interpret wildcards inside a list:  if a list element is identified as a wildcard, this is a signal that we need to expand the list before we proceed,    e.g.  with tags [tag-A, tag-B, tag-C, host, region] we can do  `group(by: ["host", "tag-*"])`  which is internally expanded to `group(by:["host", "tag-A", "tag-B", "tag-C"])`

**Comment by nathanielc** [comment]
Does InfluxQL support the group by "user_*" pattern? I am not sure what that use case is.

**Comment by aanthony1243** [comment]
couldn't tell you what it is, but regex is supported in some interesting points in a query: 
https://docs.influxdata.com/influxdb/v1.5/query_language/data_exploration/#regular-expressions

**Comment by nathanielc** [comment]
To my knowledge regex is supported as part of a query predicate, but never as part of a group by.

**Comment by aanthony1243** [comment]
@nathanielc   from the link I posted, it says 

``` InfluxQL supports using regular expressions when specifying:

field keys and tag keys in the SELECT clause
measurements in the FROM clause
tag values and string field values in the WHERE clause.
tag keys in the GROUP BY clause```

**Comment by nathanielc** [comment]
Thanks, apparently I can't read :)

Well that makes group by very difficult. Initially I think that would need to be a special argument to group like `byRegexp` which takes a list of regexp. That way normal group by syntax is not hindered by regex support but those that want it can still use it. Thoughts?

Also it seems like wildcards and regex support are similar, but we can treat them differently. Thoughts?

**Comment by aanthony1243** [comment]
I'm tempted to think:  the _query engine_ needs to support this because we need to support InfluxQL.  

But in general, this feature has made me uncomfortable when I come across it (there are examples in the monitoring queries).  The risk for combinatorial explosion is just so high, it seems hardly worth it to have an available shortcut.  

Perhaps we can isolate the column-name expansion in the transpiler code?  Isolate the wildcard expressions, use meta-queries to find out the column names, expand to a finite lies, then avoid this issue entirely in the IFQL spec. 
@jsternberg  thoughts?

**Comment by jsternberg** [comment]
I'm not sure this wildcard behavior is needed as @aanthony1243 says. The column-name expansion is going to have to be done separately anyway since I will need to generate the columns. It doesn't fit with ifql's model to use wildcards.

Especially since in most cases, functions already implement the wildcard aspects in other ways. Queries are already grouped by star by default and just having a `group(except: ["_field"])` would allow me to do everything I need. Similarly, the same is true with join. The field key is the only thing that's problematic because it makes grouping and join not actually group the keys I want and they're the only portions where I would "need" a wildcard.

**Comment by jsternberg** [comment]
I ran into an issue with the transpiler and I think this is an issue for more than just the transpiler. If you wanted to find the host with the maximum cpu usage, you could do this in InfluxQL.

```
SELECT max(usage_user), host FROM telegraf..cpu
```

But I'm not sure how to do this equivalent thing in IFQL. The reason is because this finds the max across all series so you need to use `group()` to group everything into the same bucket, but you then need to keep the `host` tag so you can return that as part of a separate column. If you use a field instead, like `usage_system`, you would need to keep all of the tags from the `group() |> max()` call so you could properly join the `usage_system` cursor to the equivalent series in `usage_user`.

It seems like the current options to `group()` don't offer an ability to group things into the same bucket, but retain the tags so they could be used for a join operation.

**Comment by adamperlin** [comment]
Kamino closed and cloned this issue to [influxdata/platform](https://github.com/influxdata/platform/issues/262)
